#spring.application.name=athletix
##server
#server.port=8080
#
## PostgreSQL
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/athletix}
#spring.datasource.username=${DB_USERNAME:postgres}
#spring.datasource.password=${DB_PASSWORD:password}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## Clerk
##clerk.webhook.secret=whsec_Sj3+6I1nH3FSE6oQAghAu2Zj+f+MSDrC
##clerk.api.key=sk_test_2RQJAxHlQ48Fk62RqRNYOGrrMyO5uOn3TtWbVkjvsj
###  pk_test_dG9nZXRoZXItbG91c2UtMzEuY2xlcmsuYWNjb3VudHMuZGV2JA
#
## JWT
#jwt.secret=f1940ca7216bbd1b2a2258b1b416a3a46362dabd833c98ff5a9e427220a43d3d
#jwt.expiration=86400000
#
## ========== Mail Configuration ==========
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=sonumagar787@gmail.com
#spring.mail.password=zoyejoehlfnamlcu
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
